In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/content/drive/My Drive/train.csv')

In [ ]:
df.head()

id  ... label
0   0  ...     1
1   1  ...     0
2   2  ...     1
3   3  ...     1
4   4  ...     1

[5 rows x 5 columns]

In [ ]:
df.shape

(20800, 5)

In [ ]:
df =df.dropna()

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20800 entries, 0 to 20799
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      20800 non-null  int64 
 1   title   20242 non-null  object
 2   author  18843 non-null  object
 3   text    20761 non-null  object
 4   label   20800 non-null  int64 
dtypes: int64(2), object(3)
memory usage: 812.6+ KB


In [ ]:
df.isnull().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [ ]:
## Get the Independent Features

X=df.drop('label',axis=1)


In [ ]:
y=df['label']

In [ ]:

import tensorflow as tf

In [ ]:
tf.__version__

'2.2.0'

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [ ]:
voc_size=5000



In [ ]:
messages=X.copy()

In [ ]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [ ]:
messages.reset_index(inplace=True)

In [ ]:
import re
import nltk
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

Streaming output truncated to the last 5000 lines.
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
13344
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
13369
13370
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
13439
13440
13441
13442
13443
1

In [ ]:
corpus[0]

'hous dem aid even see comey letter jason chaffetz tweet'

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[362, 2387, 1636, 1614, 2016, 4686, 357, 36, 124, 4504],
 [920, 1496, 765, 2120, 4396, 2232, 3880],
 [3665, 3776, 3059, 2254],
 [4782, 3047, 3749, 4738, 1794, 3626],
 [3784, 4396, 632, 1503, 285, 45, 4396, 4423, 4898, 2874],
 [2012,
  208,
  2753,
  2439,
  4917,
  4586,
  690,
  600,
  4909,
  2460,
  4715,
  3431,
  2747,
  3433,
  3880],
 [1804, 3747, 4002, 3031, 2153, 1224, 4408, 2648, 3376, 1598, 3010],
 [2876, 891, 2739, 3659, 1957, 3959, 4586, 2134, 3376, 1598, 3010],
 [3886, 760, 4866, 4554, 2759, 124, 3143, 426, 4586, 4356],
 [4161, 395, 4213, 438, 3087, 4835, 1903, 3995],
 [3650, 2482, 2744, 4719, 349, 3468, 2569, 402, 1028, 1652, 336],
 [4738, 4837, 2016, 124, 4586, 1957],
 [905, 566, 92, 2936, 1059, 984, 2391, 2834, 1746],
 [3, 2001, 2190, 931, 2073, 1372, 1807, 3376, 1598, 3010],
 [4992, 4078, 3665, 22, 1202, 3376, 1598, 3010],
 [860, 1637, 4709, 812, 1001, 42, 3557, 654, 946, 4012],
 [3950, 4100, 1496],
 [2088, 4763, 1140, 4109, 4586, 4991, 872, 3880],
 [4769, 4023, 765,

In [ ]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ...   36  124 4504]
 [   0    0    0 ... 4396 2232 3880]
 [   0    0    0 ... 3776 3059 2254]
 ...
 [   0    0    0 ... 3376 1598 3010]
 [   0    0    0 ...  878 1433  934]
 [   0    0    0 ... 3673  618 2225]]


In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,  362,
       2387, 1636, 1614, 2016, 4686,  357,   36,  124, 4504], dtype=int32)

In [ ]:
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 20, 40)            200000    
_________________________________________________________________
lstm (LSTM)                  (None, 100)               56400     
_________________________________________________________________
dense (Dense)                (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
len(embedded_docs),y.shape

(18285, (18285,))

In [ ]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [ ]:
X_final.shape,y_final.shape


((18285, 20), (18285,))

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [ ]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 7s 36ms/step - loss: 0.3480 - accuracy: 0.8403 - val_loss: 0.1967 - val_accuracy: 0.9171
Epoch 2/10
192/192 [==============================] - 6s 33ms/step - loss: 0.1482 - accuracy: 0.9415 - val_loss: 0.1888 - val_accuracy: 0.9215
Epoch 3/10
192/192 [==============================] - 6s 33ms/step - loss: 0.1092 - accuracy: 0.9602 - val_loss: 0.2102 - val_accuracy: 0.9130
Epoch 4/10
192/192 [==============================] - 6s 33ms/step - loss: 0.0873 - accuracy: 0.9684 - val_loss: 0.2235 - val_accuracy: 0.9153
Epoch 5/10
192/192 [==============================] - 6s 33ms/step - loss: 0.0639 - accuracy: 0.9786 - val_loss: 0.2633 - val_accuracy: 0.9094
Epoch 6/10
192/192 [==============================] - 6s 33ms/step - loss: 0.0486 - accuracy: 0.9839 - val_loss: 0.2949 - val_accuracy: 0.9107
Epoch 7/10
192/192 [==============================] - 6s 33ms/step - loss: 0.0374 - accuracy: 0.9870 - val_loss: 0.3944 - val_accuracy: 0.9140

In [ ]:
y_pred=model.predict_classes(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(y_test,y_pred)

array([[3107,  312],
       [ 238, 2378]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9088649544324772